// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Models;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(SkylightContext))]
    [Migration("20231116192947_DeckInfo")]
    partial class DeckInfo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Server.Models.CurbMount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CurbMountCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("MaxSkyClearHeight")
                        .HasColumnType("real");

                    b.Property<float>("MaxSkyClearWidth")
                        .HasColumnType("real");

                    b.Property<float>("OutsideCurbHeight")
                        .HasColumnType("real");

                    b.Property<float>("OutsideCurbWidth")
                        .HasColumnType("real");

                    b.Property<string>("SizeCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CurbMounts");
                });

            modelBuilder.Entity("Server.Models.DeckMount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeckMountCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("OutsideFrameHeight")
                        .HasColumnType("real");

                    b.Property<float>("OutsideFrameWidth")
                        .HasColumnType("real");

                    b.Property<float>("RoughOpeningHeight")
                        .HasColumnType("real");

                    b.Property<float>("RoughOpeningWidth")
                        .HasColumnType("real");

                    b.Property<string>("SizeCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DeckMounts");
                });

            modelBuilder.Entity("Server.Models.SelfFlash", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("OutsideFrameHeight")
                        .HasColumnType("real");

                    b.Property<float>("OutsideFrameWidth")
                        .HasColumnType("real");

                    b.Property<float>("RoughOpeningHeight")
                        .HasColumnType("real");

                    b.Property<float>("RoughOpeningWidth")
                        .HasColumnType("real");

                    b.Property<string>("SelfFlashCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SizeCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SelfFlashes");
                });
#pragma warning restore 612, 618
        }
    }
}
